// content 레이어 — 의미 네트워크(허브 + 연결) 로드맵 데이터. 순수 데이터.
// packId가 있으면 해당 카드팩으로 훈련 연결(없으면 "준비 중").
// connections: 다른 허브/주제와의 의미적 연결(탭 시 해당 허브로 이동).

export interface Topic {
  id: string;
  label: string;
  emoji: string;
  packId?: string;
}

export interface Section {
  id: string;
  title: string;
  emoji: string;
  color: string;
  topics: Topic[];
  connections?: string[];
  /** 섹션 중앙 여신 GIF 경로(없으면 기본 여신 캐릭터 사용). */
  gif?: string;
  /** 상위 그룹(예: 전공·직업 전문용어). 같은 그룹끼리 구분 배너로 묶임. */
  group?: string;
}


export const CURRICULUM: Section[] = [
  {
    id: "people",
    title: "사람",
    emoji: "👤",
    color: "#FF9600",
    connections: ["영화", "노래", "스포츠", "국가", "회사"],
    topics: [
      { id: "family", label: "가족", emoji: "👨‍👩‍👧" },
      { id: "friend", label: "친구", emoji: "🧑‍🤝‍🧑" },
      { id: "celeb", label: "유명인", emoji: "🌟" },
      { id: "actor", label: "배우", emoji: "🎭" },
      { id: "singer", label: "가수", emoji: "🎤" },
      { id: "athlete", label: "운동선수", emoji: "🏃" },
      { id: "politician", label: "정치인", emoji: "🏛️" },
      { id: "youtuber", label: "유튜버", emoji: "📹" },
      { id: "histfigure", label: "역사인물", emoji: "📜" },
      { id: "character", label: "캐릭터", emoji: "🦸" },
    ],
  },
  {
    id: "media",
    title: "미디어",
    emoji: "🎬",
    color: "#1CB0F6",
    connections: ["사람", "장소", "시대", "감정"],
    topics: [
      { id: "movie", label: "영화", emoji: "🎬", packId: "movies-ko" },
      { id: "drama", label: "드라마", emoji: "📺" },
      { id: "anime", label: "애니메이션", emoji: "🌸" },
      { id: "webtoon", label: "웹툰", emoji: "🖼️" },
      { id: "comic", label: "만화", emoji: "📖" },
      { id: "game", label: "게임", emoji: "🎮" },
      { id: "book", label: "책", emoji: "📚" },
      { id: "song", label: "노래", emoji: "🎵" },
      { id: "show", label: "공연", emoji: "🎫" },
      { id: "ott", label: "OTT", emoji: "📡" },
    ],
  },
  {
    id: "life",
    title: "생활",
    emoji: "🏠",
    color: "#58CC02",
    connections: ["기술", "음식", "건강"],
    topics: [
      { id: "brand", label: "브랜드", emoji: "🏷️" },
      { id: "restaurant", label: "음식점", emoji: "🍽️" },
      { id: "mall", label: "쇼핑몰", emoji: "🛍️" },
      { id: "bank", label: "은행", emoji: "🏦" },
      { id: "app", label: "앱", emoji: "📱" },
      { id: "car", label: "자동차", emoji: "🚗" },
      { id: "delivery", label: "배달", emoji: "🛵" },
      { id: "cvs", label: "편의점", emoji: "🏪" },
      { id: "mart", label: "마트", emoji: "🛒" },
      { id: "household", label: "생활용품", emoji: "🧴" },
    ],
  },
  {
    id: "health",
    title: "건강",
    emoji: "🩺",
    color: "#FF4B4B",
    connections: ["사람", "생활", "신체", "음식"],
    topics: [
      { id: "disease", label: "질병", emoji: "🤒" },
      { id: "medicine", label: "약", emoji: "💊" },
      { id: "hospital", label: "병원", emoji: "🏥" },
      { id: "checkup", label: "검사", emoji: "🔬" },
      { id: "doctor", label: "의사", emoji: "🩺" },
      { id: "exercise", label: "운동", emoji: "🏋️" },
      { id: "supplement", label: "영양제", emoji: "🟡" },
      { id: "symptom", label: "증상", emoji: "🤧" },
      { id: "treatment", label: "치료", emoji: "🩹" },
    ],
  },
  {
    id: "tech",
    title: "기술",
    emoji: "💻",
    color: "#CE82FF",
    connections: ["생활", "회사", "브랜드", "미디어"],
    topics: [
      { id: "ai", label: "AI", emoji: "🤖" },
      { id: "computer", label: "컴퓨터", emoji: "🖥️" },
      { id: "phone", label: "스마트폰", emoji: "📱" },
      { id: "internet", label: "인터넷", emoji: "🌐" },
      { id: "sns", label: "SNS", emoji: "💬" },
      { id: "program", label: "프로그램", emoji: "🧩" },
      { id: "techapp", label: "앱", emoji: "📲" },
      { id: "device", label: "전자기기", emoji: "🔌" },
      { id: "console", label: "게임기", emoji: "🕹️" },
    ],
  },
  {
    id: "place",
    title: "장소",
    emoji: "🌍",
    color: "#14B8C4",
    connections: ["사람", "시간", "음식", "여행"],
    topics: [
      { id: "country", label: "국가", emoji: "🏳️" },
      { id: "city", label: "도시", emoji: "🏙️" },
      { id: "tourist", label: "관광지", emoji: "🗺️" },
      { id: "school", label: "학교", emoji: "🏫" },
      { id: "company", label: "회사", emoji: "🏢" },
      { id: "market", label: "시장", emoji: "🏪" },
      { id: "placehospital", label: "병원", emoji: "🏥" },
      { id: "park", label: "공원", emoji: "🌳" },
      { id: "home", label: "집", emoji: "🏠" },
      { id: "eatery", label: "식당", emoji: "🍴" },
    ],
  },
  {
    id: "food",
    title: "음식",
    emoji: "🍽",
    color: "#FF7CA3",
    connections: ["건강", "장소", "사람", "계절"],
    topics: [
      { id: "dish", label: "음식", emoji: "🍱" },
      { id: "fruit", label: "과일", emoji: "🍎" },
      { id: "vegetable", label: "채소", emoji: "🥬" },
      { id: "drink", label: "음료", emoji: "🥤" },
      { id: "snack", label: "간식", emoji: "🍪" },
      { id: "traditional", label: "전통음식", emoji: "🍲" },
      { id: "dessert", label: "디저트", emoji: "🍰" },
      { id: "alcohol", label: "술", emoji: "🍶" },
      { id: "cooking", label: "조리", emoji: "🍳" },
    ],
  },
  {
    id: "nature",
    title: "자연",
    emoji: "🌿",
    color: "#46A302",
    connections: ["여행", "감정", "계절"],
    topics: [
      { id: "animal", label: "동물", emoji: "🐾" },
      { id: "plant", label: "식물", emoji: "🌱" },
      { id: "flower", label: "꽃", emoji: "🌸" },
      { id: "tree", label: "나무", emoji: "🌳" },
      { id: "insect", label: "곤충", emoji: "🐛" },
      { id: "sea", label: "바다", emoji: "🌊" },
      { id: "mountain", label: "산", emoji: "⛰️" },
      { id: "weather", label: "날씨", emoji: "⛅" },
      { id: "space", label: "우주", emoji: "🪐" },
    ],
  },
  {
    id: "object",
    title: "사물",
    emoji: "🧰",
    color: "#A560E8",
    connections: ["생활", "기술", "사람"],
    topics: [
      { id: "furniture", label: "가구", emoji: "🛋️" },
      { id: "tool", label: "도구", emoji: "🔧" },
      { id: "appliance", label: "전자제품", emoji: "📺" },
      { id: "clothes", label: "의류", emoji: "👕" },
      { id: "instrument", label: "악기", emoji: "🎸" },
      { id: "transport", label: "교통수단", emoji: "🚌" },
      { id: "stationery", label: "문구", emoji: "✏️" },
      { id: "toy", label: "장난감", emoji: "🧸" },
      { id: "sportsgear", label: "스포츠용품", emoji: "⚽" },
    ],
  },
  {
    id: "time",
    title: "시간·사건",
    emoji: "📅",
    color: "#F2A100",
    connections: ["사람", "장소", "미디어", "음식"],
    topics: [
      { id: "history", label: "역사", emoji: "📜" },
      { id: "holiday", label: "명절", emoji: "🎎" },
      { id: "anniversary", label: "기념일", emoji: "🎉" },
      { id: "season", label: "계절", emoji: "🍂" },
      { id: "sportsevent", label: "스포츠 행사", emoji: "🏆" },
      { id: "news", label: "뉴스", emoji: "📰" },
      { id: "era", label: "시대", emoji: "⏳" },
      { id: "festival", label: "축제", emoji: "🎆" },
      { id: "disaster", label: "재난", emoji: "🌪️" },
    ],
  },

  // ── 🧠 직업·전문 지식 ──
  {
    id: "job-medical",
    title: "의료·돌봄",
    emoji: "🏥",
    color: "#E5484D",
    group: "직업·전문 지식",
    topics: [
      { id: "job-medical-0", label: "의사", emoji: "🩺" },
      { id: "job-medical-1", label: "치과의사", emoji: "🦷" },
      { id: "job-medical-2", label: "한의사", emoji: "🌿" },
      { id: "job-medical-3", label: "간호사", emoji: "💉" },
      { id: "job-medical-4", label: "약사", emoji: "💊" },
      { id: "job-medical-5", label: "물리치료사", emoji: "🤸" },
      { id: "job-medical-6", label: "작업치료사", emoji: "🧩" },
      { id: "job-medical-7", label: "임상병리사", emoji: "🔬" },
      { id: "job-medical-8", label: "방사선사", emoji: "☢️" },
      { id: "job-medical-9", label: "응급구조사", emoji: "🚑" },
      { id: "job-medical-10", label: "요양보호사", emoji: "🧓" },
      { id: "job-medical-11", label: "간병인", emoji: "🤝" },
      { id: "job-medical-12", label: "사회복지사", emoji: "🫶" },
      { id: "job-medical-clinpsy", label: "임상심리사", emoji: "🧠" },
    ],
  },
  {
    id: "job-education",
    title: "교육·상담",
    emoji: "👨‍🏫",
    color: "#14B8C4",
    group: "직업·전문 지식",
    topics: [
      { id: "job-education-0", label: "교사", emoji: "🍎" },
      { id: "job-education-1", label: "교수", emoji: "🎓" },
      { id: "job-education-2", label: "어린이집 교사", emoji: "🧸" },
      { id: "job-education-3", label: "유치원 교사", emoji: "🖍️" },
      { id: "job-education-4", label: "학원강사", emoji: "📚" },
      { id: "job-education-5", label: "직업훈련교사", emoji: "🛠️" },
      { id: "job-education-6", label: "상담사", emoji: "💬" },
      { id: "job-education-7", label: "심리상담사", emoji: "🧠" },
    ],
  },
  {
    id: "job-it",
    title: "IT·디지털",
    emoji: "💻",
    color: "#8B5CF6",
    group: "직업·전문 지식",
    topics: [
      { id: "job-it-0", label: "프로그래머", emoji: "👨‍💻" },
      { id: "job-it-1", label: "AI 개발자", emoji: "🤖" },
      { id: "job-it-2", label: "웹 개발자", emoji: "🌐" },
      { id: "job-it-3", label: "앱 개발자", emoji: "📱" },
      { id: "job-it-4", label: "데이터 분석가", emoji: "📊" },
      { id: "job-it-5", label: "정보보안 전문가", emoji: "🔒" },
      { id: "job-it-6", label: "네트워크 관리자", emoji: "🕸️" },
      { id: "job-it-7", label: "시스템 관리자", emoji: "🖥️" },
      { id: "job-it-8", label: "게임 개발자", emoji: "🎮" },
      { id: "job-it-9", label: "UX/UI 디자이너", emoji: "🎨" },
    ],
  },
  {
    id: "job-research",
    title: "연구·과학",
    emoji: "🔬",
    color: "#0EA5E9",
    group: "직업·전문 지식",
    topics: [
      { id: "job-research-0", label: "연구원", emoji: "🔬" },
      { id: "job-research-1", label: "과학자", emoji: "🧪" },
      { id: "job-research-2", label: "실험 연구원", emoji: "🧫" },
      { id: "job-research-3", label: "통계 전문가", emoji: "📈" },
      { id: "job-research-4", label: "시험·분석 전문가", emoji: "🧮" },
    ],
  },
  {
    id: "job-construction",
    title: "건설·건축",
    emoji: "🏗️",
    color: "#64748B",
    group: "직업·전문 지식",
    topics: [
      { id: "job-construction-0", label: "건축가", emoji: "📐" },
      { id: "job-construction-1", label: "건설기술자", emoji: "🏗️" },
      { id: "job-construction-2", label: "현장소장", emoji: "👷" },
      { id: "job-construction-3", label: "목수", emoji: "🪚" },
      { id: "job-construction-4", label: "철근공", emoji: "🔩" },
      { id: "job-construction-5", label: "미장공", emoji: "🧱" },
      { id: "job-construction-6", label: "타일공", emoji: "🟫" },
      { id: "job-construction-stone", label: "석공", emoji: "🪨" },
      { id: "job-construction-brick", label: "조적공", emoji: "🧱" },
      { id: "job-construction-marble", label: "대리석 시공", emoji: "⬜" },
      { id: "job-construction-waterproof", label: "방수공", emoji: "💧" },
      { id: "job-construction-paper", label: "도배공", emoji: "🧻" },
      { id: "job-construction-sash", label: "샷시공", emoji: "🪟" },
      { id: "job-construction-7", label: "도장공", emoji: "🎨" },
      { id: "job-construction-8", label: "배관공", emoji: "🔧" },
      { id: "job-construction-9", label: "전기공", emoji: "⚡" },
      { id: "job-construction-10", label: "용접공", emoji: "🔥" },
      { id: "job-construction-11", label: "설비기사", emoji: "🛠️" },
      { id: "job-construction-12", label: "중장비 기사", emoji: "🚜" },
    ],
  },
  {
    id: "job-manufacturing",
    title: "제조·기계",
    emoji: "⚙️",
    color: "#78716C",
    group: "직업·전문 지식",
    topics: [
      { id: "job-manufacturing-0", label: "생산직", emoji: "🏭" },
      { id: "job-manufacturing-1", label: "기계조작원", emoji: "⚙️" },
      { id: "job-manufacturing-2", label: "CNC 기술자", emoji: "🔩" },
      { id: "job-manufacturing-3", label: "자동차 정비사", emoji: "🔧" },
      { id: "job-manufacturing-4", label: "정밀기계 기술자", emoji: "🛠️" },
      { id: "job-manufacturing-5", label: "금형 기술자", emoji: "🧰" },
      { id: "job-manufacturing-6", label: "품질관리", emoji: "✅" },
      { id: "job-manufacturing-7", label: "설계기사", emoji: "📐" },
    ],
  },
  {
    id: "job-logistics",
    title: "운송·물류",
    emoji: "🚚",
    color: "#00B4D8",
    group: "직업·전문 지식",
    topics: [
      { id: "job-logistics-0", label: "택시기사", emoji: "🚕" },
      { id: "job-logistics-1", label: "버스기사", emoji: "🚌" },
      { id: "job-logistics-2", label: "화물기사", emoji: "🚚" },
      { id: "job-logistics-3", label: "택배기사", emoji: "📦" },
      { id: "job-logistics-4", label: "배달기사", emoji: "🛵" },
      { id: "job-logistics-5", label: "철도기관사", emoji: "🚆" },
      { id: "job-logistics-6", label: "선박 승무원", emoji: "🚢" },
      { id: "job-logistics-7", label: "항공 승무원", emoji: "✈️" },
      { id: "job-logistics-8", label: "물류관리자", emoji: "🏷️" },
      { id: "job-logistics-9", label: "지게차 기사", emoji: "🚜" },
    ],
  },
  {
    id: "job-safety",
    title: "공공안전",
    emoji: "🚓",
    color: "#2563EB",
    group: "직업·전문 지식",
    topics: [
      { id: "job-safety-0", label: "경찰", emoji: "👮" },
      { id: "job-safety-1", label: "형사", emoji: "🕵️" },
      { id: "job-safety-2", label: "소방관", emoji: "🚒" },
      { id: "job-safety-3", label: "군인", emoji: "🪖" },
      { id: "job-safety-4", label: "교도관", emoji: "🔐" },
      { id: "job-safety-5", label: "경호원", emoji: "🕴️" },
      { id: "job-safety-6", label: "공무원", emoji: "🏛️" },
    ],
  },
  {
    id: "job-law",
    title: "법률·행정",
    emoji: "⚖️",
    color: "#6E56CF",
    group: "직업·전문 지식",
    topics: [
      { id: "job-law-0", label: "변호사", emoji: "⚖️" },
      { id: "job-law-1", label: "판사", emoji: "👨‍⚖️" },
      { id: "job-law-2", label: "검사", emoji: "📜" },
      { id: "job-law-3", label: "법무사", emoji: "📝" },
      { id: "job-law-4", label: "행정사", emoji: "🗂️" },
      { id: "job-law-5", label: "노무사", emoji: "🧾" },
      { id: "job-law-6", label: "세무사", emoji: "🏦" },
      { id: "job-law-7", label: "회계사", emoji: "📒" },
    ],
  },
  {
    id: "job-finance",
    title: "금융·비즈니스",
    emoji: "💰",
    color: "#16A34A",
    group: "직업·전문 지식",
    topics: [
      { id: "job-finance-0", label: "은행원", emoji: "🏦" },
      { id: "job-finance-1", label: "보험설계사", emoji: "🛡️" },
      { id: "job-finance-2", label: "투자 전문가", emoji: "📈" },
      { id: "job-finance-3", label: "기업인", emoji: "💼" },
      { id: "job-finance-4", label: "경영인", emoji: "📊" },
      { id: "job-finance-5", label: "마케팅", emoji: "📣" },
      { id: "job-finance-6", label: "영업", emoji: "🤝" },
      { id: "job-finance-7", label: "무역", emoji: "🚢" },
      { id: "job-finance-8", label: "구매", emoji: "🛒" },
      { id: "job-finance-9", label: "인사", emoji: "👥" },
      { id: "job-finance-10", label: "총무", emoji: "🗄️" },
    ],
  },
  {
    id: "job-retail",
    title: "판매·서비스",
    emoji: "🛍️",
    color: "#FF7CA3",
    group: "직업·전문 지식",
    topics: [
      { id: "job-retail-0", label: "판매원", emoji: "🛍️" },
      { id: "job-retail-1", label: "매장 관리자", emoji: "🏬" },
      { id: "job-retail-2", label: "백화점 직원", emoji: "🛒" },
      { id: "job-retail-3", label: "편의점 직원", emoji: "🏪" },
      { id: "job-retail-4", label: "호텔 직원", emoji: "🏨" },
      { id: "job-retail-5", label: "여행사 직원", emoji: "🧳" },
      { id: "job-retail-6", label: "항공서비스", emoji: "✈️" },
      { id: "job-retail-7", label: "고객상담원", emoji: "🎧" },
    ],
  },
  {
    id: "job-foodjob",
    title: "음식·외식",
    emoji: "🍳",
    color: "#FB923C",
    group: "직업·전문 지식",
    topics: [
      { id: "job-foodjob-0", label: "요리사", emoji: "👨‍🍳" },
      { id: "job-foodjob-1", label: "조리사", emoji: "🍳" },
      { id: "job-foodjob-2", label: "제과사", emoji: "🧁" },
      { id: "job-foodjob-3", label: "제빵사", emoji: "🥐" },
      { id: "job-foodjob-4", label: "바리스타", emoji: "☕" },
      { id: "job-foodjob-5", label: "소믈리에", emoji: "🍷" },
      { id: "job-foodjob-6", label: "영양사", emoji: "🥗" },
      { id: "job-foodjob-7", label: "외식업", emoji: "🍽️" },
    ],
  },
  {
    id: "job-beauty",
    title: "미용·패션",
    emoji: "💇",
    color: "#DB2777",
    group: "직업·전문 지식",
    topics: [
      { id: "job-beauty-0", label: "미용사", emoji: "💇" },
      { id: "job-beauty-1", label: "이용사", emoji: "💈" },
      { id: "job-beauty-2", label: "메이크업 아티스트", emoji: "💄" },
      { id: "job-beauty-3", label: "피부관리사", emoji: "🧖" },
      { id: "job-beauty-4", label: "네일아티스트", emoji: "💅" },
      { id: "job-beauty-5", label: "스타일리스트", emoji: "🪮" },
      { id: "job-beauty-6", label: "패션디자이너", emoji: "👗" },
      { id: "job-beauty-7", label: "의상제작", emoji: "🧵" },
    ],
  },
  {
    id: "job-agri",
    title: "농림·축산·수산",
    emoji: "🌾",
    color: "#65A30D",
    group: "직업·전문 지식",
    topics: [
      { id: "job-agri-0", label: "농업", emoji: "🌾" },
      { id: "job-agri-1", label: "원예", emoji: "🪴" },
      { id: "job-agri-2", label: "축산", emoji: "🐄" },
      { id: "job-agri-3", label: "낙농", emoji: "🥛" },
      { id: "job-agri-4", label: "양봉", emoji: "🐝" },
      { id: "job-agri-5", label: "임업", emoji: "🌲" },
      { id: "job-agri-6", label: "어업", emoji: "🎣" },
      { id: "job-agri-7", label: "양식업", emoji: "🐟" },
    ],
  },
  {
    id: "job-facility",
    title: "생활·시설관리",
    emoji: "🧹",
    color: "#0D9488",
    group: "직업·전문 지식",
    topics: [
      { id: "job-facility-0", label: "청소 전문가", emoji: "🧹" },
      { id: "job-facility-1", label: "환경미화원", emoji: "♻️" },
      { id: "job-facility-2", label: "경비원", emoji: "💂" },
      { id: "job-facility-3", label: "시설관리원", emoji: "🛠️" },
      { id: "job-facility-4", label: "세탁 전문가", emoji: "🧺" },
      { id: "job-facility-5", label: "가사관리사", emoji: "🏠" },
      { id: "job-facility-6", label: "건물관리", emoji: "🏢" },
    ],
  },
  {
    id: "job-artjob",
    title: "문화·예술",
    emoji: "🎨",
    color: "#EC4899",
    group: "직업·전문 지식",
    topics: [
      { id: "job-artjob-0", label: "화가", emoji: "🎨" },
      { id: "job-artjob-1", label: "공예가", emoji: "🧵" },
      { id: "job-artjob-2", label: "도예가", emoji: "🏺" },
      { id: "job-artjob-3", label: "조각가", emoji: "🗿" },
      { id: "job-artjob-4", label: "서예가", emoji: "🖌️" },
      { id: "job-artjob-5", label: "사진작가", emoji: "📷" },
      { id: "job-artjob-6", label: "디자이너", emoji: "✏️" },
      { id: "job-artjob-7", label: "일러스트레이터", emoji: "🖍️" },
      { id: "job-artjob-8", label: "만화가", emoji: "📖" },
      { id: "job-artjob-9", label: "웹툰 작가", emoji: "🖼️" },
      { id: "job-artjob-10", label: "작가", emoji: "✍️" },
      { id: "job-artjob-11", label: "시인", emoji: "📜" },
      { id: "job-artjob-12", label: "음악가", emoji: "🎵" },
      { id: "job-artjob-13", label: "작곡가", emoji: "🎼" },
      { id: "job-artjob-14", label: "연주자", emoji: "🎻" },
      { id: "job-artjob-15", label: "성악가", emoji: "🎤" },
      { id: "job-artjob-16", label: "배우", emoji: "🎭" },
      { id: "job-artjob-17", label: "무용가", emoji: "💃" },
      { id: "job-artjob-18", label: "안무가", emoji: "🕺" },
      { id: "job-artjob-19", label: "연출가", emoji: "🎬" },
      { id: "job-artjob-20", label: "공연기획자", emoji: "🎫" },
      { id: "job-artjob-21", label: "큐레이터", emoji: "🏛️" },
      { id: "job-artjob-22", label: "문화예술교육사", emoji: "🎓" },
    ],
  },
  {
    id: "job-mediajob",
    title: "방송·미디어",
    emoji: "📺",
    color: "#1CB0F6",
    group: "직업·전문 지식",
    topics: [
      { id: "job-mediajob-0", label: "기자", emoji: "📰" },
      { id: "job-mediajob-1", label: "아나운서", emoji: "🎙️" },
      { id: "job-mediajob-2", label: "PD", emoji: "🎬" },
      { id: "job-mediajob-3", label: "방송작가", emoji: "📝" },
      { id: "job-mediajob-4", label: "영상편집자", emoji: "✂️" },
      { id: "job-mediajob-5", label: "촬영감독", emoji: "🎥" },
      { id: "job-mediajob-6", label: "음향기사", emoji: "🎧" },
      { id: "job-mediajob-7", label: "유튜버", emoji: "📹" },
      { id: "job-mediajob-8", label: "스트리머", emoji: "📡" },
      { id: "job-mediajob-9", label: "콘텐츠 크리에이터", emoji: "✨" },
    ],
  },
  {
    id: "job-sportsjob",
    title: "스포츠",
    emoji: "⚽",
    color: "#FF9600",
    group: "직업·전문 지식",
    topics: [
      { id: "job-sportsjob-0", label: "운동선수", emoji: "🏃" },
      { id: "job-sportsjob-1", label: "감독", emoji: "📋" },
      { id: "job-sportsjob-2", label: "코치", emoji: "📣" },
      { id: "job-sportsjob-3", label: "심판", emoji: "🟨" },
      { id: "job-sportsjob-4", label: "트레이너", emoji: "💪" },
      { id: "job-sportsjob-5", label: "스포츠지도사", emoji: "🏅" },
      { id: "job-sportsjob-6", label: "재활운동 전문가", emoji: "🤸" },
    ],
  },
  {
    id: "job-religionjob",
    title: "종교",
    emoji: "✝️",
    color: "#B8860B",
    group: "직업·전문 지식",
    topics: [
      { id: "job-religionjob-0", label: "목사", emoji: "✝️" },
      { id: "job-religionjob-1", label: "신부", emoji: "⛪" },
      { id: "job-religionjob-2", label: "스님", emoji: "☸️" },
      { id: "job-religionjob-3", label: "교무", emoji: "🛐" },
      { id: "job-religionjob-4", label: "선교사", emoji: "🌍" },
      { id: "job-religionjob-5", label: "종교교육자", emoji: "📖" },
    ],
  },
  {
    id: "job-startup",
    title: "자영업·창업",
    emoji: "🏪",
    color: "#F59E0B",
    group: "직업·전문 지식",
    topics: [
      { id: "job-startup-0", label: "자영업자", emoji: "🏪" },
      { id: "job-startup-1", label: "소상공인", emoji: "🛒" },
      { id: "job-startup-2", label: "창업가", emoji: "🚀" },
      { id: "job-startup-3", label: "프랜차이즈 운영", emoji: "🍔" },
      { id: "job-startup-4", label: "온라인 판매자", emoji: "💻" },
    ],
  },
  {
    id: "job-etc",
    title: "기타",
    emoji: "👨‍👩‍👧",
    color: "#94A3B8",
    group: "직업·전문 지식",
    topics: [
      { id: "job-etc-0", label: "주부", emoji: "🏠" },
      { id: "job-etc-1", label: "학생", emoji: "🎒" },
      { id: "job-etc-2", label: "취업준비생", emoji: "📄" },
      { id: "job-etc-3", label: "프리랜서", emoji: "💻" },
      { id: "job-etc-4", label: "은퇴자", emoji: "🌅" },
      { id: "job-etc-5", label: "기타", emoji: "➕" },
    ],
  },
];
